export { default as Navbar } from "./navbar/Navbar";
export { default as Hero } from "./hero/Hero";
export { default as Second } from "./second/Second";
export { default as Third } from "./third/Third";
export { default as Fourth } from "./fourth/Fourth";
export { default as Footer } from "./footer/Footer";

// Images
export { default as Logo } from "../assets/logo.svg";
export { default as Vector } from "../assets/Vector.svg";
export { default as searchIcon } from "../assets/searchIcon.svg";
export { default as sunSolid } from "../assets/sun-white.svg";
export { default as moonSolid } from "../assets/moon-white.svg";
export { default as sparkles } from "../assets/sparkles.svg";
export { default as img } from "../assets/img.png";
export { default as arrowRight } from "../assets/arrowRight.svg";
export { default as arrowRight2 } from "../assets/arrowRight2.svg";
export { default as wide } from "../assets/wide.svg";
export { default as starStroke } from "../assets/starStroke.svg";
export { default as save } from "../assets/save.svg";
export { default as rectangle } from "../assets/Rectangle.png";
export { default as firstSec } from "../assets/firstSec.png";
export { default as secondSec } from "../assets/secondSec.png";
export { default as editorFrame } from "../assets/editorFrame.png";
export { default as Instagram } from "../assets/Instagram.svg";
export { default as Facebook } from "../assets/Facebook.svg";
export { default as Twitter } from "../assets/Twitter.svg";
export { default as Linkedin } from "../assets/LinkedIn.svg";
export { default as arrowUp } from "../assets/arrowUp.svg";